name: Azure CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:

  azure_login:
    runs-on: ubuntu-24.04
    steps:
    - name: Azure Login
      uses: azure/login@v2
      env:
        AZURE_LOGIN_PRE_CLEANUP: true
        AZURE_LOGIN_POST_CLEANUP: true
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az group list --output table

  debug:
    runs-on: ubuntu-24.04
    steps:
    # steps to run custom scripts
    - name: Run a multi-line script
      run: |
        echo "::debug::Set the Octocat variable as an environment variable"
        echo ::notice title=Set the Octocat variable::export OCTOCAT="🐙"
        echo "::debug:: Value of GITHUB_API_URL is $GITHUB_API_URL"
        echo "::debug:: Value of GITHUB_GRAPHQL_URL is $GITHUB_GRAPHQL_URL"
        



      
