name: Azure CI pipeline
run-name: Azure CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  azure_login:
    runs-on: ubuntu-24.04
    environment: engineering
    steps:
    - name: Azure Login
      id: azure_login
      uses: azure/login@v2
      env:
        AZURE_LOGIN_PRE_CLEANUP: true
        AZURE_LOGIN_POST_CLEANUP: true
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Azure CLI script
      id: azure_cli_script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az group list --output table

    - name: Azure CLI Account Info
      uses: azure/cli@v2
      id: azure-account
      env:
        ACTIONS_STEP_DEBUG: true
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        azcliversion: latest
        inlineScript: |
          account_info=$(az account show)
          echo "SUBSCRIPTION_ID=$(echo $account_info | jq -r .id)" >> $GITHUB_OUTPUT
          echo "TENANT_ID=$(echo $account_info | jq -r .tenantId)" >> $GITHUB_OUTPUT
          echo 'AZ_CLI_VERSION=$(az version --output=json | jq -r ".[\"azure-cli\"]")' >> $GITHUB_OUTPUT

    - name: Debug step
      run: |
        echo "::debug::SUBSCRIPTION_ID is ${{ steps.azure-account.outputs.SUBSCRIPTION_ID }}"
        echo "::debug::AZ_CLI_VERSION is ${{ steps.azure-account.outputs.AZ_CLI_VERSION }}"
  
    # - name: Set output variables
    #   id: set_outputs
    #   run: |
    #     echo "azcliversion=$(az version --output tsv --query \"azure-cli\")" >> $GITHUB_OUTPUT
    #     echo "account=$(az account show --query \"user.name\" -o tsv)" >> $GITHUB_OUTPUT
    #     echo "subscription=$(az account show --query \"name\" -o tsv)" >> $GITHUB_OUTPUT
    #     echo "::debug::CLI version is ${{ steps.azure_cli_script.outputs.azcliversion }}"

    outputs:
      AZURE_CLI_VERSION: ${{ steps.azure-account.outputs.AZ_CLI_VERSION }}
  
  debug:
    runs-on: ubuntu-24.04
    environment: engineering
    needs: azure_login
    steps:
    # steps to run custom scripts
    - name: Run a multi-line script
      run: |
        echo "::debug::Set the Octocat variable as an environment variable"
        echo ::notice title=Set the Octocat variable::export OCTOCAT="🐙"
        echo "::debug:: Value of GITHUB_API_URL is $GITHUB_API_URL"
        echo "::debug:: Value of GITHUB_GRAPHQL_URL is $GITHUB_GRAPHQL_URL"
        echo "::debug:: CLI version is ${{ needs.azure_login.outputs.AZURE_CLI_VERSION }}"




      
