name: JavaScript CI Pipeline

on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]

jobs:
    build:
        runs-on: ubuntu-24.04
        
        strategy:
            matrix:
                node-version: [18.x]

        steps:
        - uses: actions/checkout@v3
        
        - name: Verify workspace
          run: |
            echo "Current working directory: $(pwd)"
            echo "Directory contents:"
            ls -la
            if [ ! -f "package.json" ]; then
              echo "Error: package.json not found!"
              exit 1
            fi
        
        - name: Setup Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
                
        - name: Install dependencies
          if: success()
          timeout-minutes: 10
          run: |
            npm install eslint --save-dev
            npm install
          env:
            NODE_OPTIONS: "--max-old-space-size=4096"
        
        - name: Initialize ESLint
          run: |
            echo "Creating ESLint config..."
            cat > .eslintrc.yml << EOF
            env:
              node: true
              es2021: true
            extends:
              - 'eslint:recommended'
            parserOptions:
              ecmaVersion: 2021
              sourceType: module
            rules:
              indent: ['error', 2]
              quotes: ['error', 'single']
              semi: ['error', 'always']
            EOF
        
        - name: Run linting
          if: success()
          run: |
            echo "Running linter..."
            ./node_modules/.bin/eslint . --ext .js || exit 1
        
        - name: Run tests
          if: success()
          run: npm test
            
        - name: Build project
          if: success()
          run: npm run build
            
        - name: Upload build artifacts
          if: success()
          uses: actions/upload-artifact@v3
          with:
            name: build-files
            path: dist/

        - name: Run security audit
          run: npm audit
